import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'login_screen.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:google_sign_in/google_sign_in.dart';

class SettingsScreen extends StatelessWidget {
  const SettingsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Settings"),
      ),
      body: ListView(
        children: [

          ListTile(
            leading: const Icon(Icons.privacy_tip),
            title: const Text("Privacy Policy"),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (_) => const PrivacyPolicyScreen(),
                ),
              );
            },
          ),

          ListTile(
            leading: const Icon(Icons.info),
            title: const Text("About Hunter Ascend"),
            onTap: () {
              showAboutDialog(
                context: context,
                applicationName: "Hunter Ascend",
                applicationVersion: "1.0.0",
                children: const [
                  Text(
                    "Level Up Your Real Life.",
                  ),
                ],
              );
            },
          ),
          ListTile(
            leading: const Icon(
              Icons.logout,
              color: Colors.red,
            ),
            title: const Text(
              "Logout",
              style: TextStyle(
                color: Colors.red,
              ),
            ),
            onTap: () async {
              final user = FirebaseAuth.instance.currentUser;

              if (user != null && user.isAnonymous) {
                await FirebaseFirestore.instance
                    .collection('hunters')
                    .doc(user.uid)
                    .delete();
                await user.delete();
              } else {
                await GoogleSignIn().signOut();
                await FirebaseAuth.instance.signOut();
              }

              // ✅ No Navigator needed — StreamBuilder in main.dart
              // will detect signout and route to LoginScreen automatically
if (context.mounted) {
Navigator.of(context).popUntil((route) => route.isFirst);
}
            },
          ),
        ],
      ),
    );
  }
}

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Privacy Policy"),
      ),
      body: const Padding(
        padding: EdgeInsets.all(16),
        child: SingleChildScrollView(
          child: Text(
            '''
# Privacy Policy for Hunter Ascend: Fitness Duels

Last Updated: June 2026

Hunter Ascend: Fitness Duels ("the App") is committed to protecting your privacy. This Privacy Policy explains how information is collected, used, and protected when you use the App.

## Information We Collect

The App may collect and store the following information:

* User authentication information provided through Firebase Authentication.
* Anonymous user identifiers generated by Firebase.
* Profile information such as Hunter Name and Profile Picture (if provided).
* Fitness challenge and duel-related information.
* Progress data including XP, levels, wins, losses, streaks, and achievements.
* Technical information necessary for app functionality and security.

## How We Use Information

We use collected information to:

* Create and manage user accounts.
* Enable fitness duels and challenges.
* Track progress and achievements.
* Improve app functionality and performance.
* Prevent abuse, cheating, and unauthorized access.

## Firebase Services

Hunter Ascend uses Google Firebase services, including:

* Firebase Authentication
* Cloud Firestore
* Firebase Storage (if profile pictures are enabled)

These services may collect information as described in Google's Privacy Policy.

## Profile Pictures

If you choose to upload a profile picture, the image will be stored securely and displayed within the app as part of your profile.

## Data Security

Reasonable measures are taken to protect user information from unauthorized access, alteration, or disclosure. However, no internet-based service can guarantee complete security.

## Children's Privacy

The App is not directed toward children under the age of 13. We do not knowingly collect personal information from children under 13.

## Third-Party Services

The App may use third-party services such as Google Firebase and advertising services in future versions.

## Your Choices

You may stop using the App at any time. If account deletion functionality becomes available, users may request removal of their data.

## Changes to This Privacy Policy

This Privacy Policy may be updated periodically. Any updates will be posted on this page.

## Contact

For questions regarding this Privacy Policy, contact:

Email: [jefferinlal@gmail.com](mailto:jefferinlal@gmail.com)

''',
            style: TextStyle(
              fontSize: 16,
            ),
          ),
        ),
      ),
    );
  }
}